Error from logcat:
[ 07-20 17:47:23.997 19271:19961 W/         ]
 Unable to open '/system/framework/dpmapi.jar': No such file or directory

 java.lang.RuntimeException: Error receiving broadcast Intent { act=com.websmithing.broadcasttest.displayevent flg=0x10 bqHint=4 VirtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)} (has extras) } in com.example.alesha.percomsg.UserProfile$3@c144a0

 /////////////////////////////////////////////////////////////////////////////////////////

 This class was working fine up until I started to add in new code from the gesture detection projects. Maybe I forgot to add something, I am not sure. I tested the background service and made sure it communicated with the UserProfile and it did. Then it started to throw out this error.